import "./admin.css";
import { ToasterProvider } from "@/context/ToasterProvider";
import NavBar from "./admin/ui/NavBar";
import SideBar from "./admin/ui/SideBar";
import "@uploadthing/react/styles.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="h-[80px] md:pl-56 flex inset-y-0 w-full z-50">
          <NavBar/>
        </div>
        <div className="hidden md:flex h-full w-56 fixed flex-col inset-y-0 z-56">
           <SideBar/>
        </div>
       <main className="md:pl-56 pt-[80px] h-full">
       <ToasterProvider/>
        {children}
       </main>
        </body>
    </html>
  )
}
